### ISSUE TITLE
dl_abu_model didn't provide

### ISSUE THREAD

**Issue by kai0416s** [aguarda/IT-DL-PCC#1]
Thank you for your open source excellent work.
Could you  provide more details about the dl_abu_model in train_SR.py or clarify what specific functionality it should include? 
This will help me create a suitable implementation.
This information will be helpful to me.
 I look forward to your response.Thanks.

**Comment by aguarda** [comment]
Hi! Thank you for your comments.

It was a naming error, the dl_abu_model was supposed to be the dl_sr_model. I fixed it in the new commit 5098f47ff3080d5e56ef9fe3214559783bdc671e .

Hope this helps.
